name: "Run PiGrow"
author: ethanjli
description: Grows a Raspberry Pi SD card image, decompressing it if necessary.
branding:
  icon: maximize-2
  color: red

inputs:
  image:
    description: Path of the image to grow
    required: true
  destination:
    description: Path to write the grown image to
    required: false
  mode:
    description:
      Grow the image by the specified size, or grow the image to at least the specified size.
      Allowed values are `by`, `to`, and `none`.
    required: false
    default: none
  size:
    description:
      Grow the image by the specified size, or to at least the specified size.
    required: false
    default: 0

outputs:
  destination:
    description: Path of the shrunken image
    value: ${{ steps.run-pigrow.outputs.destination }}

runs:
  using: composite
  steps:
    - id: run-pigrow
      shell: bash
      env:
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_DESTINATION: ${{ inputs.destination }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_SIZE: ${{ inputs.size }}
      run: |
        destination="$INPUT_DESTINATION"
        if [ -z "$destination" ]; then
          destination="$(mktemp --tmpdir=/tmp raw-image.XXXXXXX)"
        fi
        echo "destination=$destination" >> $GITHUB_OUTPUT

        case "$INPUT_MODE" in
          by)
            echo "Growing $destination by $INPUT_SIZE..."
            adjustment="+$INPUT_SIZE"
            ;;
          to)
            echo "Growing $destination to at least $INPUT_SIZE..."
            adjustment=">$INPUT_SIZE"
            ;;
          none | '')
            adjustment=""
            ;;
          *)
            echo "Error: unrecognized mode: $INPUT_MODE"
            exit 1
            ;;
        esac

        ${{ github.action_path }}/pigrow.sh "$INPUT_IMAGE" "$destination" "$adjustment"
