name: build-os
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  merge_group:
  workflow_dispatch:

jobs:
  build:
    name: Build test image
    strategy:
      fail-fast: false
      matrix:
        destination:
          - name: implicit
            path: ''
          - name: explicit
            path: 'destination.img'
          - name: explicit-gz
            path: 'destination.img.gz'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download a base image
        run: |
          wget https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-03-15/2024-03-15-raspios-bookworm-arm64-lite.img.xz

      - name: Grow the image
        id: grow-image
        uses: ./
        with:
          image: 2024-03-15-raspios-bookworm-arm64-lite.img.xz
          destination: ${{ matrix.destination.path }}
          mode: by
          size: 8G

      - name: Build the image
        run: |
          sudo apt-get install systemd-container qemu-user-static binfmt-support
          device="$(losetup -fP --show ${{ steps.grow-image.outputs.destination }})"
          sudo systemd-nspawn --image "${device}p2" bash -c "\
            apt-get update
            apt-get install -y cowsay
            /usr/games/cowsay 'I am running in a namespace container!'
          "
          sudo losetup -d "$device"

      - name: Shrink the image
        uses: ethanjli/pishrink-action@v0.1.1
        with:
          image: ${{ steps.grow-image.outputs.destination }}
          destination: cowsay-image.img
          compress: gzip
          compress-parallel: true

      - name: Upload image to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpi-${{ matrix.destination.name }}-arm64-latest
          path: cowsay-image.img
          if-no-files-found: error
          retention-days: 0
          overwrite: true
